"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 60

format = "($username )($hostname )$directory ($git_branch )($git_commit )$git_state$git_status$character"
right_format = "($status )($cmd_duration )($jobs )($python )($rust )$time"

[character]
error_symbol = "\\$"
success_symbol = "\\$"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_symbol = "[](bold green)"
vimcmd_visual_symbol = "[](bold yellow)"

[cmd_duration]
format = "[ $duration]($style)"
style = "yellow"

[directory]
fish_style_pwd_dir_length = 1
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold blue"

[git_branch]
format = "[$symbol$branch]($style)"
style = "green"
symbol = " "

[git_commit]
commit_hash_length = 8
format = "[$hash$tag]($style)"
style = "green"

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
conflicted = "$count"
deleted = "-$count"
diverged = "⇡$ahead_count⇣$behind_count"
format = "[($conflicted )](red)[($stashed )](magenta)[($staged )](green)[($deleted )](red)[($renamed )](blue)[($modified )](yellow)[($untracked )](blue)[($ahead_behind )](green)"
modified = "!$count"
renamed = "→$count"
staged = "+$count"
stashed = "\\$$count"
untracked = "?$count"

[hostname]
format = "[$hostname]($style)[$ssh_symbol](green)"
ssh_only = true
ssh_symbol = " 󰣀"
style = "bold red"

[python]
format = "[$symbol$pyenv_prefix($version )(($virtualenv) )]($style)"

[status]
disabled = false
format = "[$status( $signal_name)]($style)"
pipestatus = true
pipestatus_format = "$pipestatus => [$int( $signal_name)]($style)"
pipestatus_segment_format = "[$status]($style)"
pipestatus_separator = "[|]($style)"
style = "red"

[time]
disabled = false
format = "[ $time]($style)"
style = "cyan"

[username]
format = "[$user]($style)"
style_root = "bold red"
style_user = "bold purple"

[username.aliases]
root = ""
